server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/VadimUpdate/Configs
          default-label: main  # или master, если у тебя так называется ветка
